# Generated by Django 4.1.6 on 2023-02-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografias_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='data_foto',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 9, 41, 40, 504404)),
        ),
    ]
