# Generated by Django 4.1.6 on 2023-02-11 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografias_data_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='data_foto',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 10, 8, 11, 509214)),
        ),
        migrations.AlterField(
            model_name='fotografias',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
