# Generated by Django 4.1.6 on 2023-02-14 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografias_data_foto_alter_fotografias_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='data_foto',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 18, 12, 28, 819817)),
        ),
        migrations.AlterField(
            model_name='fotografias',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
